#!/usr/bin/env ruby
require 'test/unit'
require 'colorize'
# Also:
# require 'cucumber'

class TestCucumber < Test::Unit::TestCase
  def test_cucumber
    flunk 'Rotten cucumber!'.red unless system 'cucumber -f progress'
  end
end
