#!/usr/bin/env ruby
require 'test/unit'
require 'rafini/odometers'

class TestOdometers < Test::Unit::TestCase
  using Rafini::Odometers

  def test_sec2time_to_s
    assert_nothing_raised() do
      assert_equal '10 seconds', 10.sec2time.to_s
      assert_equal '1 minute and 40 seconds', 100.sec2time.to_s
      assert_equal '16 minutes and 41 seconds', 1_001.sec2time.to_s
      assert_equal '2 hours and 46 minutes', 10_000.sec2time.to_s
      assert_equal '1 day and 3 hours', 100_000.sec2time.to_s
      assert_equal '1 week and 4 days', 1_000_000.sec2time.to_s
      assert_equal '3 months and 3 weeks', 10_000_000.sec2time.to_s
      assert_equal '3 years and 2 months', 100_000_000.sec2time.to_s
      assert_equal '3 decades and 1 year', 1_000_000_000.sec2time.to_s
      assert_equal '3 centuries and 1 decade', 10_000_000_000.sec2time.to_s
      assert_equal '3 millenniums and 1 centurie', 100_000_000_000.sec2time.to_s
      assert_equal '3 ages and 1 millennium', 1_000_000_000_000.sec2time.to_s
      assert_equal '3 epochs and 1 age', 10_000_000_000_000.sec2time.to_s
      assert_equal '3 eras and 1 epoch', 100_000_000_000_000.sec2time.to_s
      assert_equal '1 eon and 4 eras', 300_000_000_000_000.sec2time.to_s
      assert_equal '3 gigaannums', 1_000_000_000_000_000.sec2time.to_s
      assert_equal '31 gigaannums and 1 eon', 10_000_000_000_000_000.sec2time.to_s
    end
  end

  def test_sec2time_to_struct
    assert_nothing_raised() do
      assert_equal 10, 10.sec2time.second
      assert_equal 1, 100.sec2time.minute
      assert_equal 41, 1_001.sec2time.second
      assert_equal 2, 10_000.sec2time.hour
      assert_equal 1, 100_000.sec2time.day
      assert_equal 1, 1_000_000.sec2time.week
      assert_equal 3, 10_000_000.sec2time.month
      assert_equal 3, 100_000_000.sec2time.year
      assert_equal 3, 1_000_000_000.sec2time.decade
      assert_equal 3, 10_000_000_000.sec2time.centurie
      assert_equal 3, 100_000_000_000.sec2time.millennium
      assert_equal 3, 1_000_000_000_000.sec2time.age
      assert_equal 3, 10_000_000_000_000.sec2time.epoch
      assert_equal 3, 100_000_000_000_000.sec2time.era
      assert_equal 1, 300_000_000_000_000.sec2time.eon
      assert_equal 3, 1_000_000_000_000_000.sec2time.gigaannum
      assert_equal 1, 10_000_000_000_000_000.sec2time.eon
    end
  end

  def test_illion_to_s
    assert_nothing_raised() do
      assert_equal '123', 123.illion.to_s
      assert_equal '1.23K', 1_234.illion.to_s
      assert_equal '12.3K', 12_344.illion.to_s
      assert_equal '123K', 123_456.illion.to_s
      assert_equal '1.23M', 1_234_567.illion.to_s
      assert_equal '12.3M', 12_345_678.illion.to_s
      assert_equal '123M', 123_456_789.illion.to_s

      assert_equal '1.23B', 1_234_567_890.illion(:short).to_s
      assert_equal '1.23KM', 1_234_567_890.illion(:long).to_s

      assert_equal '12.3B', 12_345_678_900.illion(:short).to_s
      assert_equal '12.3KM', 12_345_678_900.illion(:long).to_s

      assert_equal '123B', 123_456_789_000.illion(:short).to_s
      assert_equal '123KM', 123_456_789_000.illion(:long).to_s

      assert_equal '1.23T', 1_234_567_890_000.illion(:short).to_s
      assert_equal '1.23B', 1_234_567_890_000.illion(:long).to_s

      assert_equal '12.3T', 12345678900000.illion(:short).to_s
      assert_equal '12.3B', 12345678900000.illion(:long).to_s

      assert_equal '123T', 123456789000000.illion(:short).to_s
      assert_equal '123B', 123456789000000.illion(:long).to_s

      assert_equal '1.23Q',  1234567890000000.illion.to_s # short default
      assert_equal '1.23KB', 1234567890000000.illion(:long).to_s

      assert_equal '12.3Q',  12345678900000000.illion.to_s
      assert_equal '12.3KB', 12345678900000000.illion(:long).to_s

      assert_equal '123Q',  123456789000000000.illion.to_s
      assert_equal '123KB', 123456789000000000.illion(:long).to_s

      assert_equal '1.23KQ',  1234567890000000000.illion.to_s
      # short version works, but
      # use does not make sense for numbers bigger that Quadrillion
      # as coded.  Needs Quintillion, and so on...
      # Unless one likes 1.23kQ, recurses nicely as shown:
      q = 1000000000000000
      assert_equal '1.0Q', q.illion.to_s
      assert_equal '1.0QQ', (q*q).illion.to_s

      assert_equal '1.23T', 1234567890000000000.illion(:long).to_s
      assert_equal '12.3T',  12345678900000000000.illion(:long).to_s
      assert_equal '123T',   123456789000000000000.illion(:long).to_s
      assert_equal '1.23KT', 1234567890000000000000.illion(:long).to_s
      assert_equal '12.3KT', 12345678900000000000000.illion(:long).to_s
      assert_equal '123KT',  123456789000000000000000.illion(:long).to_s
      assert_equal '1.23Q',  1234567890000000000000000.illion(:long).to_s
      assert_equal '1.23KQ', 1234567890000000000000000000.illion(:long).to_s
      assert_equal '123KQ',  123456789000000000000000000000.illion(:long).to_s
      assert_equal '1.23MQ', 1234567890000000000000000000000.illion(:long).to_s
      # long version works, but
      # use does not make sense for numbers bigger than KQ, Thousand-Quadrillions
      # as coded.  Needs Quintillion, and so on...
      # Unless one likes MQ, and so on, it recurses nicely as show below:
      qs =             1_000_000_000_000_000
      ql = 1_000_000_000_000_000_000_000_000
      assert_equal '1.0Q', qs.illion(:short).to_s
      assert_equal '1.0Q', ql.illion(:long).to_s
      assert_equal '1.0QQ', (qs*ql).illion(:long).to_s

    end
  end

  def test_illion_struct
    assert_nothing_raised() do
      m = 888_777_666_555_444_321.illion
      assert_equal m.one, 1
      assert_equal m.ten, 2
      assert_equal m.hundred, 3
      assert_equal m.thousand, 444
      assert_equal m.million, 555
      assert_equal m.billion, 666
      assert_equal m.trillion, 777
      assert_equal m.quadrillion, 888
      assert_equal "889Q", m.to_s
    end
  end
end
