#!/usr/bin/env ruby
require 'test/unit'
require 'rafini'

class TestRequires < Test::Unit::TestCase
  using Rafini::Requires
  def test_satisfies
    assert_equal false, '1.1'.satisfies?('>1.1', '<1.3')
    assert_equal true, ' 1.2'.satisfies?('>1.1', '<1.3')
    assert_equal false, '1.3'.satisfies?('>1.1', '<1.3')

    assert_equal false, '2.6.9'.satisfies?('~>2.7')
    assert_equal true,  '2.7.0'.satisfies?('~>2.7')
    assert_equal true, ' 2.9.9'.satisfies?('~>2.7')
    assert_equal false, '3.0.0'.satisfies?('~>2.7')
  end

  def test_requires
    # NOTE: README tests `requires` as a refinement.
    loaded = Rafini.requires'
    rafini ~>3.1
    ruby ~>3.0
    json ~>2.0'
    assert_equal ['json'], loaded
  end
end
