AllCops:
  NewCops: enable
Layout/ArgumentAlignment:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/LineLength:
  Max: 80
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAroundBlockParameters:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false
Lint/Debugger:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/InheritException:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
